name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 mypy types-requests types-python-dateutil
        pip install -e .
        
    - name: Check formatting with black
      run: black --check notunsplash tests examples
        
    - name: Lint with flake8
      run: flake8 notunsplash tests examples --max-line-length=100
        
    - name: Type check with mypy
      run: mypy notunsplash --strict
